### ISSUE TITLE
Hey just wondering, Can you guide me on getting the data.

### ISSUE THREAD

**Issue by HelloIshHere** [riju-stone/chatbot#1]
I am looking for where Do I get the CSV data from JRC1995 chatbot project, could you guide me and help me out please.

**Comment by riju-stone** [comment]
Sure. You will find two .sql files here https://github.com/riju-stone/chatbot/tree/main/V3%20-%20HybridTTS/Large_Scale_Retriever/data .
One for fetching the posts (questions) and another for comments (answers). Change the subreddit clause inside the query to fetch data from a particular subreddit.
You will need to use Google BigQuery SQL console to fetch these data and store then as csv data. I suggest registering for a trial account for 60 days. I had some issues with registering that why I couldn't fetch the data. Hope it works for you.
Good luck
